### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by UniverseObserver** [JBossOutreach/compressor-head-android#70]
![xxxhdpi](https://user-images.githubusercontent.com/30717258/33546628-7eeda226-d91c-11e7-86fb-591a26dcb9ba.png)
![xhdpi](https://user-images.githubusercontent.com/30717258/33546629-7f1d693e-d91c-11e7-80ad-b6c5874cb5f2.png)
![xxhdpi](https://user-images.githubusercontent.com/30717258/33546633-7fd387c8-d91c-11e7-9dcd-c6fc49f18a0e.png)
![hdpi](https://user-images.githubusercontent.com/30717258/33546636-81fc735c-d91c-11e7-978a-9bcb20c025c4.png)
![mdpi](https://user-images.githubusercontent.com/30717258/33546637-8230d08e-d91c-11e7-8781-d33f14e6696f.png)

**Comment by aashutoshrathi** [comment]
Please Always add at least a brief description of issues created.
